export const BlockId = {
  Air: 0,
  Verdant: 1,
  Loam: 2,
  Slate: 3,
  Dune: 4,
  Timber: 5,
  Canopy: 6,
  Water: 7,
  CopperBloom: 8,
  GlowCrystal: 9,
  SunShardOre: 10,
  DuskShardOre: 11,
  SunShard: 12,
  DuskShard: 13,
  SunEgg: 14,
  EmptyFlask: 15,
  MeadowMilk: 16,
  CloudWool: 17,
  FieldSeed: 18,
  Sungrain: 19,
  TrailRation: 20,
  TrailTool: 21,
  FiberShears: 22,
  FieldDoor: 23,
  StorageChest: 24,
  CraftStation: 25,
  ProcessorStation: 26,
  FarmStation: 27,
  NexusWorkbench: 28,
  TrailPath: 29,
  ResonantPlant: 30,
  Tideglass: 31,
  OldComponent: 32,
  SettlerComponent: 33,
  NodeCalibrator: 34,
  RefinedAlloy: 35,
  NexusConduit: 36,
  DeepAlloy: 37,
  FrequencyCore: 38,
  WaygateFuel: 39,
  NexusLight: 40,
  ExpeditionFood: 41,
  ExpeditionGear: 42,
  SpectrumCrystal: 43,
  MachineKit: 44,
  CoreFragment: 45,
  EndgameComponent: 46,
  AllianceSeal: 47,
  CoreFuel: 48,
  NexusDevice: 49,
  RawSunroot: 50,
  CookedSunroot: 51,
  FuelCell: 52,
  RootSeed: 53,
  Sunroot: 54,
  CultivatedLoam: 55,
} as const;

export type BlockIdValue = (typeof BlockId)[keyof typeof BlockId];

export interface BlockDefinition {
  id: BlockIdValue;
  key: string;
  name: string;
  color: readonly [number, number, number];
  solid: boolean;
  transparent: boolean;
  hardness: number;
  drop: BlockIdValue | null;
  lootTableId?: string;
  metadataSchema: "none" | "fluid-level" | "orientation";
}

export const BLOCKS: readonly BlockDefinition[] = [
  {
    id: BlockId.Air,
    key: "air",
    name: "空氣",
    color: [0, 0, 0],
    solid: false,
    transparent: true,
    hardness: 0,
    drop: null,
    metadataSchema: "none",
  },
  {
    id: BlockId.Verdant,
    key: "verdant",
    name: "青原塊",
    color: [0.26, 0.58, 0.31],
    solid: true,
    transparent: false,
    hardness: 0.8,
    drop: BlockId.Loam,
    metadataSchema: "none",
  },
  {
    id: BlockId.Loam,
    key: "loam",
    name: "壤土",
    color: [0.43, 0.29, 0.18],
    solid: true,
    transparent: false,
    hardness: 0.7,
    drop: BlockId.Loam,
    metadataSchema: "none",
  },
  {
    id: BlockId.Slate,
    key: "slate",
    name: "深紋岩",
    color: [0.35, 0.39, 0.42],
    solid: true,
    transparent: false,
    hardness: 1.7,
    drop: BlockId.Slate,
    metadataSchema: "none",
  },
  {
    id: BlockId.Dune,
    key: "dune",
    name: "星砂",
    color: [0.82, 0.69, 0.39],
    solid: true,
    transparent: false,
    hardness: 0.5,
    drop: BlockId.Dune,
    metadataSchema: "none",
  },
  {
    id: BlockId.Timber,
    key: "timber",
    name: "琥珀木",
    color: [0.53, 0.33, 0.16],
    solid: true,
    transparent: false,
    hardness: 1.2,
    drop: BlockId.Timber,
    metadataSchema: "orientation",
  },
  {
    id: BlockId.Canopy,
    key: "canopy",
    name: "雲葉",
    color: [0.19, 0.48, 0.3],
    solid: true,
    transparent: true,
    hardness: 0.3,
    drop: BlockId.Canopy,
    metadataSchema: "none",
  },
  {
    id: BlockId.Water,
    key: "water",
    name: "清泉",
    color: [0.16, 0.49, 0.73],
    solid: false,
    transparent: true,
    hardness: 100,
    drop: null,
    metadataSchema: "fluid-level",
  },
  {
    id: BlockId.CopperBloom,
    key: "copper-bloom",
    name: "銅花礦",
    color: [0.67, 0.39, 0.25],
    solid: true,
    transparent: false,
    hardness: 2.2,
    drop: BlockId.CopperBloom,
    metadataSchema: "none",
  },
  {
    id: BlockId.GlowCrystal,
    key: "glow-crystal",
    name: "輝晶",
    color: [0.35, 0.82, 0.79],
    solid: true,
    transparent: false,
    hardness: 2.6,
    drop: BlockId.GlowCrystal,
    metadataSchema: "none",
  },
  {
    id: BlockId.SunShardOre,
    key: "sun-shard-ore",
    name: "日耀晶礦",
    color: [0.95, 0.72, 0.2],
    solid: true,
    transparent: false,
    hardness: 3.1,
    drop: BlockId.SunShard,
    lootTableId: "ore:sun-shard",
    metadataSchema: "none",
  },
  {
    id: BlockId.DuskShardOre,
    key: "dusk-shard-ore",
    name: "暮影晶礦",
    color: [0.57, 0.27, 0.78],
    solid: true,
    transparent: false,
    hardness: 3.4,
    drop: BlockId.DuskShard,
    lootTableId: "ore:dusk-shard",
    metadataSchema: "none",
  },
  {
    id: BlockId.SunShard,
    key: "sun-shard",
    name: "日耀晶",
    color: [1, 0.82, 0.28],
    solid: true,
    transparent: false,
    hardness: 1,
    drop: BlockId.SunShard,
    lootTableId: "item:sun-shard",
    metadataSchema: "none",
  },
  {
    id: BlockId.DuskShard,
    key: "dusk-shard",
    name: "暮影晶",
    color: [0.65, 0.38, 0.9],
    solid: true,
    transparent: false,
    hardness: 1,
    drop: BlockId.DuskShard,
    lootTableId: "item:dusk-shard",
    metadataSchema: "none",
  },
  {
    id: BlockId.SunEgg,
    key: "sun-egg",
    name: "晨光蛋",
    color: [0.94, 0.86, 0.62],
    solid: false,
    transparent: true,
    hardness: 0.2,
    drop: BlockId.SunEgg,
    metadataSchema: "none",
  },
  {
    id: BlockId.EmptyFlask,
    key: "empty-flask",
    name: "空野行瓶",
    color: [0.55, 0.75, 0.78],
    solid: false,
    transparent: true,
    hardness: 0.4,
    drop: BlockId.EmptyFlask,
    metadataSchema: "none",
  },
  {
    id: BlockId.MeadowMilk,
    key: "meadow-milk",
    name: "牧野乳",
    color: [0.96, 0.94, 0.8],
    solid: false,
    transparent: true,
    hardness: 0.3,
    drop: BlockId.MeadowMilk,
    metadataSchema: "none",
  },
  {
    id: BlockId.CloudWool,
    key: "cloud-wool",
    name: "雲絨",
    color: [0.83, 0.88, 0.9],
    solid: true,
    transparent: false,
    hardness: 0.4,
    drop: BlockId.CloudWool,
    metadataSchema: "none",
  },
  {
    id: BlockId.FieldSeed,
    key: "field-seed",
    name: "日穗種子",
    color: [0.63, 0.68, 0.22],
    solid: false,
    transparent: true,
    hardness: 0.1,
    drop: BlockId.FieldSeed,
    metadataSchema: "none",
  },
  {
    id: BlockId.Sungrain,
    key: "sungrain",
    name: "日穗",
    color: [0.88, 0.68, 0.22],
    solid: false,
    transparent: true,
    hardness: 0.2,
    drop: BlockId.Sungrain,
    metadataSchema: "none",
  },
  {
    id: BlockId.TrailRation,
    key: "trail-ration",
    name: "遠行糧",
    color: [0.73, 0.43, 0.21],
    solid: false,
    transparent: true,
    hardness: 0.2,
    drop: BlockId.TrailRation,
    metadataSchema: "none",
  },
  {
    id: BlockId.TrailTool,
    key: "trail-tool",
    name: "拓荒鑿",
    color: [0.43, 0.68, 0.71],
    solid: false,
    transparent: true,
    hardness: 0.5,
    drop: BlockId.TrailTool,
    metadataSchema: "none",
  },
  {
    id: BlockId.FiberShears,
    key: "fiber-shears",
    name: "纖維剪",
    color: [0.72, 0.78, 0.76],
    solid: false,
    transparent: true,
    hardness: 0.5,
    drop: BlockId.FiberShears,
    metadataSchema: "none",
  },
  {
    id: BlockId.CultivatedLoam,
    key: "cultivated-loam",
    name: "培田土",
    color: [0.34, 0.22, 0.13],
    solid: true,
    transparent: false,
    hardness: 0.65,
    drop: BlockId.Loam,
    metadataSchema: "none",
  },
  ...(
    [
      [BlockId.FieldDoor, "field-door", "風木門", [0.48, 0.29, 0.14], true],
      [BlockId.StorageChest, "chest", "方域儲存箱", [0.58, 0.38, 0.16], true],
      [
        BlockId.CraftStation,
        "craft-station",
        "組構台",
        [0.36, 0.55, 0.59],
        true,
      ],
      [
        BlockId.ProcessorStation,
        "processor",
        "脈熱加工站",
        [0.42, 0.44, 0.46],
        true,
      ],
      [BlockId.FarmStation, "farm-station", "育種台", [0.38, 0.59, 0.3], true],
      [
        BlockId.NexusWorkbench,
        "workstation",
        "Nexus 工程台",
        [0.27, 0.72, 0.76],
        true,
      ],
      [BlockId.TrailPath, "path", "星砂路磚", [0.69, 0.58, 0.37], true],
      [
        BlockId.ResonantPlant,
        "forest-plant",
        "共鳴蕨",
        [0.3, 0.75, 0.46],
        false,
      ],
      [BlockId.Tideglass, "tideglass", "潮汐玻晶", [0.26, 0.72, 0.9], true],
      [
        BlockId.OldComponent,
        "old-component",
        "遺留零件",
        [0.58, 0.51, 0.4],
        false,
      ],
      [
        BlockId.SettlerComponent,
        "settler-component",
        "工匠零件",
        [0.77, 0.57, 0.25],
        false,
      ],
      [
        BlockId.NodeCalibrator,
        "node-calibrator",
        "節點校準器",
        [0.36, 0.83, 0.76],
        false,
      ],
      [
        BlockId.RefinedAlloy,
        "refined-material",
        "穩相合金",
        [0.68, 0.76, 0.77],
        false,
      ],
      [
        BlockId.NexusConduit,
        "nexus-conduit",
        "Nexus 導管",
        [0.22, 0.8, 0.8],
        true,
      ],
      [BlockId.DeepAlloy, "deep-alloy", "深層合金", [0.28, 0.38, 0.49], false],
      [
        BlockId.FrequencyCore,
        "frequency-core",
        "頻率核心",
        [0.75, 0.35, 0.86],
        false,
      ],
      [
        BlockId.WaygateFuel,
        "waygate-fuel",
        "躍遷燃料",
        [0.88, 0.61, 0.2],
        false,
      ],
      [
        BlockId.NexusLight,
        "nexus-light",
        "Nexus 光標",
        [0.65, 0.96, 0.91],
        true,
      ],
      [
        BlockId.ExpeditionFood,
        "expedition-food",
        "遠征補給",
        [0.79, 0.42, 0.2],
        false,
      ],
      [
        BlockId.ExpeditionGear,
        "expedition-gear",
        "遠征裝備",
        [0.33, 0.58, 0.66],
        false,
      ],
      [
        BlockId.SpectrumCrystal,
        "crystal-spectrum",
        "光譜晶簇",
        [0.8, 0.47, 0.88],
        false,
      ],
      [
        BlockId.MachineKit,
        "machine-kit",
        "機械修復組",
        [0.55, 0.64, 0.65],
        false,
      ],
      [
        BlockId.CoreFragment,
        "core-fragment",
        "核心碎片",
        [0.88, 0.32, 0.49],
        false,
      ],
      [
        BlockId.EndgameComponent,
        "endgame-component",
        "終局元件",
        [0.31, 0.86, 0.77],
        false,
      ],
      [
        BlockId.AllianceSeal,
        "alliance-seal",
        "聚落聯盟印記",
        [0.86, 0.67, 0.23],
        false,
      ],
      [BlockId.CoreFuel, "core-fuel", "核心燃料", [0.94, 0.42, 0.2], false],
      [
        BlockId.NexusDevice,
        "nexus-device",
        "Nexus 終端裝置",
        [0.36, 0.94, 0.89],
        true,
      ],
      [BlockId.RawSunroot, "raw-sunroot", "生日根", [0.64, 0.37, 0.18], false],
      [
        BlockId.CookedSunroot,
        "cooked-sunroot",
        "烤日根",
        [0.86, 0.52, 0.22],
        false,
      ],
      [BlockId.FuelCell, "fuel-cell", "脈熱燃芯", [0.9, 0.45, 0.17], false],
      [BlockId.RootSeed, "root-seed", "日根種子", [0.55, 0.48, 0.18], false],
      [BlockId.Sunroot, "sunroot", "日根", [0.75, 0.4, 0.18], false],
    ] as const
  ).map(([id, key, name, color, solid]) => ({
    id,
    key,
    name,
    color,
    solid,
    transparent: !solid,
    hardness: solid ? 1.2 : 0.2,
    drop: id,
    metadataSchema: "none" as const,
  })),
] as const;

export interface LootDrop {
  itemId: BlockIdValue;
  count: number;
}
export function getBlockLoot(blockId: BlockIdValue): readonly LootDrop[] {
  const block = getBlockDefinition(blockId);
  if (blockId === BlockId.Canopy)
    return [
      { itemId: BlockId.Canopy, count: 1 },
      { itemId: BlockId.FieldSeed, count: 1 },
    ];
  return block.drop === null ? [] : [{ itemId: block.drop, count: 1 }];
}

const blocksById = new Map(BLOCKS.map((block) => [block.id, block]));
export const MAX_BLOCK_ID = Math.max(...BLOCKS.map((block) => block.id));

export function getBlockDefinition(id: number): BlockDefinition {
  return blocksById.get(id as BlockIdValue) ?? BLOCKS[0]!;
}
