export const BlockId = {
  Air: 0,
  Verdant: 1,
  Loam: 2,
  Slate: 3,
  Dune: 4,
  Timber: 5,
  Canopy: 6,
  Water: 7,
  CopperBloom: 8,
  GlowCrystal: 9,
  SunShardOre: 10,
  DuskShardOre: 11,
  SunShard: 12,
  DuskShard: 13,
  SunEgg: 14,
  EmptyFlask: 15,
  MeadowMilk: 16,
  CloudWool: 17,
  FieldSeed: 18,
  Sungrain: 19,
  TrailRation: 20,
  TrailTool: 21,
  FiberShears: 22,
} as const;

export type BlockIdValue = (typeof BlockId)[keyof typeof BlockId];

export interface BlockDefinition {
  id: BlockIdValue;
  key: string;
  name: string;
  color: readonly [number, number, number];
  solid: boolean;
  transparent: boolean;
  hardness: number;
  drop: BlockIdValue | null;
  lootTableId?: string;
  metadataSchema: "none" | "fluid-level" | "orientation";
}

export const BLOCKS: readonly BlockDefinition[] = [
  {
    id: BlockId.Air,
    key: "air",
    name: "空氣",
    color: [0, 0, 0],
    solid: false,
    transparent: true,
    hardness: 0,
    drop: null,
    metadataSchema: "none",
  },
  {
    id: BlockId.Verdant,
    key: "verdant",
    name: "青原塊",
    color: [0.26, 0.58, 0.31],
    solid: true,
    transparent: false,
    hardness: 0.8,
    drop: BlockId.Loam,
    metadataSchema: "none",
  },
  {
    id: BlockId.Loam,
    key: "loam",
    name: "壤土",
    color: [0.43, 0.29, 0.18],
    solid: true,
    transparent: false,
    hardness: 0.7,
    drop: BlockId.Loam,
    metadataSchema: "none",
  },
  {
    id: BlockId.Slate,
    key: "slate",
    name: "深紋岩",
    color: [0.35, 0.39, 0.42],
    solid: true,
    transparent: false,
    hardness: 1.7,
    drop: BlockId.Slate,
    metadataSchema: "none",
  },
  {
    id: BlockId.Dune,
    key: "dune",
    name: "星砂",
    color: [0.82, 0.69, 0.39],
    solid: true,
    transparent: false,
    hardness: 0.5,
    drop: BlockId.Dune,
    metadataSchema: "none",
  },
  {
    id: BlockId.Timber,
    key: "timber",
    name: "琥珀木",
    color: [0.53, 0.33, 0.16],
    solid: true,
    transparent: false,
    hardness: 1.2,
    drop: BlockId.Timber,
    metadataSchema: "orientation",
  },
  {
    id: BlockId.Canopy,
    key: "canopy",
    name: "雲葉",
    color: [0.19, 0.48, 0.3],
    solid: true,
    transparent: true,
    hardness: 0.3,
    drop: BlockId.Canopy,
    metadataSchema: "none",
  },
  {
    id: BlockId.Water,
    key: "water",
    name: "清泉",
    color: [0.16, 0.49, 0.73],
    solid: false,
    transparent: true,
    hardness: 100,
    drop: null,
    metadataSchema: "fluid-level",
  },
  {
    id: BlockId.CopperBloom,
    key: "copper-bloom",
    name: "銅花礦",
    color: [0.67, 0.39, 0.25],
    solid: true,
    transparent: false,
    hardness: 2.2,
    drop: BlockId.CopperBloom,
    metadataSchema: "none",
  },
  {
    id: BlockId.GlowCrystal,
    key: "glow-crystal",
    name: "輝晶",
    color: [0.35, 0.82, 0.79],
    solid: true,
    transparent: false,
    hardness: 2.6,
    drop: BlockId.GlowCrystal,
    metadataSchema: "none",
  },
  {
    id: BlockId.SunShardOre,
    key: "sun-shard-ore",
    name: "日耀晶礦",
    color: [0.95, 0.72, 0.2],
    solid: true,
    transparent: false,
    hardness: 3.1,
    drop: BlockId.SunShard,
    lootTableId: "ore:sun-shard",
    metadataSchema: "none",
  },
  {
    id: BlockId.DuskShardOre,
    key: "dusk-shard-ore",
    name: "暮影晶礦",
    color: [0.57, 0.27, 0.78],
    solid: true,
    transparent: false,
    hardness: 3.4,
    drop: BlockId.DuskShard,
    lootTableId: "ore:dusk-shard",
    metadataSchema: "none",
  },
  {
    id: BlockId.SunShard,
    key: "sun-shard",
    name: "日耀晶",
    color: [1, 0.82, 0.28],
    solid: true,
    transparent: false,
    hardness: 1,
    drop: BlockId.SunShard,
    lootTableId: "item:sun-shard",
    metadataSchema: "none",
  },
  {
    id: BlockId.DuskShard,
    key: "dusk-shard",
    name: "暮影晶",
    color: [0.65, 0.38, 0.9],
    solid: true,
    transparent: false,
    hardness: 1,
    drop: BlockId.DuskShard,
    lootTableId: "item:dusk-shard",
    metadataSchema: "none",
  },
  {
    id: BlockId.SunEgg,
    key: "sun-egg",
    name: "晨光蛋",
    color: [0.94, 0.86, 0.62],
    solid: false,
    transparent: true,
    hardness: 0.2,
    drop: BlockId.SunEgg,
    metadataSchema: "none",
  },
  {
    id: BlockId.EmptyFlask,
    key: "empty-flask",
    name: "空野行瓶",
    color: [0.55, 0.75, 0.78],
    solid: false,
    transparent: true,
    hardness: 0.4,
    drop: BlockId.EmptyFlask,
    metadataSchema: "none",
  },
  {
    id: BlockId.MeadowMilk,
    key: "meadow-milk",
    name: "牧野乳",
    color: [0.96, 0.94, 0.8],
    solid: false,
    transparent: true,
    hardness: 0.3,
    drop: BlockId.MeadowMilk,
    metadataSchema: "none",
  },
  {
    id: BlockId.CloudWool,
    key: "cloud-wool",
    name: "雲絨",
    color: [0.83, 0.88, 0.9],
    solid: true,
    transparent: false,
    hardness: 0.4,
    drop: BlockId.CloudWool,
    metadataSchema: "none",
  },
  {
    id: BlockId.FieldSeed,
    key: "field-seed",
    name: "日穗種子",
    color: [0.63, 0.68, 0.22],
    solid: false,
    transparent: true,
    hardness: 0.1,
    drop: BlockId.FieldSeed,
    metadataSchema: "none",
  },
  {
    id: BlockId.Sungrain,
    key: "sungrain",
    name: "日穗",
    color: [0.88, 0.68, 0.22],
    solid: false,
    transparent: true,
    hardness: 0.2,
    drop: BlockId.Sungrain,
    metadataSchema: "none",
  },
  {
    id: BlockId.TrailRation,
    key: "trail-ration",
    name: "遠行糧",
    color: [0.73, 0.43, 0.21],
    solid: false,
    transparent: true,
    hardness: 0.2,
    drop: BlockId.TrailRation,
    metadataSchema: "none",
  },
  {
    id: BlockId.TrailTool,
    key: "trail-tool",
    name: "拓荒鑿",
    color: [0.43, 0.68, 0.71],
    solid: false,
    transparent: true,
    hardness: 0.5,
    drop: BlockId.TrailTool,
    metadataSchema: "none",
  },
  {
    id: BlockId.FiberShears,
    key: "fiber-shears",
    name: "纖維剪",
    color: [0.72, 0.78, 0.76],
    solid: false,
    transparent: true,
    hardness: 0.5,
    drop: BlockId.FiberShears,
    metadataSchema: "none",
  },
] as const;

export interface LootDrop {
  itemId: BlockIdValue;
  count: number;
}
export function getBlockLoot(blockId: BlockIdValue): readonly LootDrop[] {
  const block = getBlockDefinition(blockId);
  if (blockId === BlockId.Canopy)
    return [
      { itemId: BlockId.Canopy, count: 1 },
      { itemId: BlockId.FieldSeed, count: 1 },
    ];
  return block.drop === null ? [] : [{ itemId: block.drop, count: 1 }];
}

const blocksById = new Map(BLOCKS.map((block) => [block.id, block]));

export function getBlockDefinition(id: number): BlockDefinition {
  return blocksById.get(id as BlockIdValue) ?? BLOCKS[0]!;
}
